### PR TITLE
Uploading multiple images

### LINKED ISSUE #2: Uploading multiple images
Currently the endpoint for handling uploads takes in one image. It should be able to accept up to 12 images - the number of images should be set via the config var (`CALENDAGO_UPLOAD_MAX_IMAGES`)

### PR DESCRIPTION
**Pull request by TgkCapture**
Fixes #2

### CODE REVIEW

**Comment by TgkCapture** [comment]
having problems with (file) where there is fileHeader.open()... on line 38

**Comment by zikani03** [comment]
@TgkCapture I've pushed a commit to fix the implementation. Please take a look

It also seems like you pushed the changes to main before sending the PR 🙈

**Review by TgkCapture — COMMENTED** [review]
viewed the changes....

**Comment by TgkCapture** [comment]
we can proceed?

**Pull request merged**
